services:
  db:
    image: postgis/postgis:15-3.3
    container_name: rentavan-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: rentavan_db
    ports:
      - "5432:5432"
    volumes:
      - rentavan_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  rentavan_data:
